server:
  port: 8080

database:
  host: "localhost"
  port: 5432
  user: "cook"
  password: "cook_password"
  dbname: "cook_db"
  sslmode: "disable"

oss:
  endpoint: "http://oss-cn-beijing.aliyuncs.com"
  access_key_id: "your_access_key_id"
  access_key_secret: "your_access_key_secret"
  bucket_name: "your_bucket_name"
  base_path: "meals/"

